# Generated by Django 4.1.7 on 2023-06-06 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name="KeepaExcelAU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Buy_Price_BB", models.FloatField(blank=True, null=True)),
                ("Buy_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Buy_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_BB", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Referral_Fee_Percentage", models.FloatField(blank=True, null=True)),
                ("Pick_and_Pack_Fee", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeepaExcelCA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Buy_Price_BB", models.FloatField(blank=True, null=True)),
                ("Buy_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Buy_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_BB", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Referral_Fee_Percentage", models.FloatField(blank=True, null=True)),
                ("Pick_and_Pack_Fee", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeepaExcelDE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Buy_Price_BB", models.FloatField(blank=True, null=True)),
                ("Buy_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Buy_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_BB", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Referral_Fee_Percentage", models.FloatField(blank=True, null=True)),
                ("Pick_and_Pack_Fee", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeepaExcelFR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Buy_Price_BB", models.FloatField(blank=True, null=True)),
                ("Buy_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Buy_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_BB", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Referral_Fee_Percentage", models.FloatField(blank=True, null=True)),
                ("Pick_and_Pack_Fee", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeepaExcelJA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Buy_Price_BB", models.FloatField(blank=True, null=True)),
                ("Buy_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Buy_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_BB", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Referral_Fee_Percentage", models.FloatField(blank=True, null=True)),
                ("Pick_and_Pack_Fee", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KeepaExcelUK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Buy_Price_BB", models.FloatField(blank=True, null=True)),
                ("Buy_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Buy_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_NC", models.FloatField(blank=True, null=True)),
                ("Sale_Price_BB", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBM", models.FloatField(blank=True, null=True)),
                ("Sale_Price_FBA", models.FloatField(blank=True, null=True)),
                ("Referral_Fee_Percentage", models.FloatField(blank=True, null=True)),
                ("Pick_and_Pack_Fee", models.FloatField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotCompletedAU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotCompletedCA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotCompletedDE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotCompletedFR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotCompletedJA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotCompletedUK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoreLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Link", models.CharField(blank=True, max_length=500, null=True)),
                ("Marketplace", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompletedUK",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price", models.FloatField(blank=True, null=True)),
                ("Sale_Price", models.FloatField(blank=True, null=True)),
                ("Ratio", models.FloatField(blank=True, null=True)),
                ("Cost", models.FloatField(blank=True, null=True)),
                ("Profit", models.FloatField(blank=True, null=True)),
                ("Profit_Percentage", models.FloatField(blank=True, null=True)),
                ("Sales_Info", models.IntegerField(blank=True, null=True)),
                ("Date", models.DateTimeField(blank=True, null=True)),
                ("Fba_Seller_Count", models.IntegerField(blank=True, null=True)),
                (
                    "Is_Buybox_Fba",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "Is_Amazon_Selling",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("Pool", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompletedJA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price", models.FloatField(blank=True, null=True)),
                ("Sale_Price", models.FloatField(blank=True, null=True)),
                ("Ratio", models.FloatField(blank=True, null=True)),
                ("Cost", models.FloatField(blank=True, null=True)),
                ("Profit", models.FloatField(blank=True, null=True)),
                ("Profit_Percentage", models.FloatField(blank=True, null=True)),
                ("Sales_Info", models.IntegerField(blank=True, null=True)),
                ("Date", models.DateTimeField(blank=True, null=True)),
                ("Fba_Seller_Count", models.IntegerField(blank=True, null=True)),
                (
                    "Is_Buybox_Fba",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "Is_Amazon_Selling",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("Pool", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompletedFR",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price", models.FloatField(blank=True, null=True)),
                ("Sale_Price", models.FloatField(blank=True, null=True)),
                ("Ratio", models.FloatField(blank=True, null=True)),
                ("Cost", models.FloatField(blank=True, null=True)),
                ("Profit", models.FloatField(blank=True, null=True)),
                ("Profit_Percentage", models.FloatField(blank=True, null=True)),
                ("Sales_Info", models.IntegerField(blank=True, null=True)),
                ("Date", models.DateTimeField(blank=True, null=True)),
                ("Fba_Seller_Count", models.IntegerField(blank=True, null=True)),
                (
                    "Is_Buybox_Fba",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "Is_Amazon_Selling",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("Pool", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompletedDE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price", models.FloatField(blank=True, null=True)),
                ("Sale_Price", models.FloatField(blank=True, null=True)),
                ("Ratio", models.FloatField(blank=True, null=True)),
                ("Cost", models.FloatField(blank=True, null=True)),
                ("Profit", models.FloatField(blank=True, null=True)),
                ("Profit_Percentage", models.FloatField(blank=True, null=True)),
                ("Sales_Info", models.IntegerField(blank=True, null=True)),
                ("Date", models.DateTimeField(blank=True, null=True)),
                ("Fba_Seller_Count", models.IntegerField(blank=True, null=True)),
                (
                    "Is_Buybox_Fba",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "Is_Amazon_Selling",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("Pool", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompletedCA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price", models.FloatField(blank=True, null=True)),
                ("Sale_Price", models.FloatField(blank=True, null=True)),
                ("Ratio", models.FloatField(blank=True, null=True)),
                ("Cost", models.FloatField(blank=True, null=True)),
                ("Profit", models.FloatField(blank=True, null=True)),
                ("Profit_Percentage", models.FloatField(blank=True, null=True)),
                ("Sales_Info", models.IntegerField(blank=True, null=True)),
                ("Date", models.DateTimeField(blank=True, null=True)),
                ("Fba_Seller_Count", models.IntegerField(blank=True, null=True)),
                (
                    "Is_Buybox_Fba",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "Is_Amazon_Selling",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("Pool", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompletedAU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=100, null=True)),
                ("Asin", models.CharField(blank=True, max_length=100, null=True)),
                ("SalesRank", models.IntegerField(blank=True, null=True)),
                ("Drop_Count", models.IntegerField(blank=True, null=True)),
                ("Buy_Price", models.FloatField(blank=True, null=True)),
                ("Sale_Price", models.FloatField(blank=True, null=True)),
                ("Ratio", models.FloatField(blank=True, null=True)),
                ("Cost", models.FloatField(blank=True, null=True)),
                ("Profit", models.FloatField(blank=True, null=True)),
                ("Profit_Percentage", models.FloatField(blank=True, null=True)),
                ("Sales_Info", models.IntegerField(blank=True, null=True)),
                ("Date", models.DateTimeField(blank=True, null=True)),
                ("Fba_Seller_Count", models.IntegerField(blank=True, null=True)),
                (
                    "Is_Buybox_Fba",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "Is_Amazon_Selling",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("Pool", models.BooleanField(blank=True, default=False, null=True)),
                (
                    "User",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
