# Generated by Django 4.1.7 on 2023-06-07 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote", "0002_alter_completedau_title_alter_completedca_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keepaexcelau",
            name="Title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelca",
            name="Title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelde",
            name="Title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelfr",
            name="Title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelja",
            name="Title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexceluk",
            name="Title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
