# Generated by Django 4.1.7 on 2023-06-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote", "0003_alter_keepaexcelau_title_alter_keepaexcelca_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="completedau",
            name="Is_Amazon_Selling",
        ),
        migrations.RemoveField(
            model_name="completedca",
            name="Is_Amazon_Selling",
        ),
        migrations.RemoveField(
            model_name="completedde",
            name="Is_Amazon_Selling",
        ),
        migrations.RemoveField(
            model_name="completedfr",
            name="Is_Amazon_Selling",
        ),
        migrations.RemoveField(
            model_name="completedja",
            name="Is_Amazon_Selling",
        ),
        migrations.RemoveField(
            model_name="completeduk",
            name="Is_Amazon_Selling",
        ),
        migrations.AddField(
            model_name="completedau",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedca",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedde",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedfr",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedja",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completeduk",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="completedau",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completedca",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completedde",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completedfr",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completedja",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completeduk",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelau",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelca",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelde",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelfr",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelja",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexceluk",
            name="Title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
