# Generated by Django 4.1.7 on 2023-06-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote", "0006_alter_completedau_date_alter_completedca_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedau",
            name="Error_Code",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completedau",
            name="Is_Deleted_By_User",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completedau",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedca",
            name="Error_Code",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completedca",
            name="Is_Deleted_By_User",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completedca",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedde",
            name="Error_Code",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completedde",
            name="Is_Deleted_By_User",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completedde",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedfr",
            name="Error_Code",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completedfr",
            name="Is_Deleted_By_User",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completedfr",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedja",
            name="Error_Code",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completedja",
            name="Is_Deleted_By_User",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completedja",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completeduk",
            name="Error_Code",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completeduk",
            name="Is_Deleted_By_User",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="completeduk",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="completedau",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completedau",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="completedca",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completedca",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="completedde",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completedde",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="completedfr",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completedfr",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="completedja",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completedja",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="completeduk",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="completeduk",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelau",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelca",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelde",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelfr",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexcelja",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="keepaexceluk",
            name="Asin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
