# Generated by Django 4.1.7 on 2023-06-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote", "0007_completedau_error_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keepaexcelau",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelau",
            name="Fba_Seller_Count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelau",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelau",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelca",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelca",
            name="Fba_Seller_Count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelca",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelca",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelde",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelde",
            name="Fba_Seller_Count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelde",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelde",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelfr",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelfr",
            name="Fba_Seller_Count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelfr",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelfr",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelja",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelja",
            name="Fba_Seller_Count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelja",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelja",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexceluk",
            name="Amazon_Current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexceluk",
            name="Fba_Seller_Count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexceluk",
            name="Is_Buybox_Fba",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexceluk",
            name="Weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
