# Generated by Django 4.1.7 on 2023-06-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("remote", "0008_keepaexcelau_amazon_current_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedau",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedau",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedau",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedca",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedca",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedca",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedde",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedde",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedde",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedfr",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedfr",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedfr",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedja",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedja",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completedja",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completeduk",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completeduk",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="completeduk",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelau",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelau",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelau",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelca",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelca",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelca",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelde",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelde",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelde",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelfr",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelfr",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelfr",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelja",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelja",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexcelja",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexceluk",
            name="Buybox_Lowest",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexceluk",
            name="SalesRank90",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="keepaexceluk",
            name="Variation_Asins",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
