# Generated by Django 4.1.7 on 2023-10-15 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("remote", "0009_completedau_buybox_lowest_completedau_salesrank90_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="excelData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Market", models.CharField(blank=True, max_length=5, null=True)),
                ("com_asin", models.FileField(upload_to="amazon2/remote/keepa_files")),
                (
                    "target_asin",
                    models.FileField(upload_to="amazon2/remote/keepa_files"),
                ),
                ("Is_executed", models.BooleanField(default=False)),
                ("DateTime", models.DateTimeField(blank=True, null=True)),
                (
                    "Userx",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
