# Generated by Django 4.1.7 on 2023-10-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("remote", "0010_exceldata"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoreLink",
        ),
    ]
