# Generated by Django 4.1.1 on 2022-12-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_exceldata"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="MALIYET",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
