# Generated by Django 4.1.1 on 2023-02-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_data_maliyet"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="DEPO_MALIYET",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exceldata",
            name="file",
            field=models.FileField(upload_to="attachment/%Y/%m/%d"),
        ),
    ]
