# Generated by Django 4.1.1 on 2023-02-14 17:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_data_depo_maliyet_alter_exceldata_file"),
    ]

    operations = [
        migrations.RenameModel(old_name="Data", new_name="Ingiltere",),
    ]
