# Generated by Django 4.1.1 on 2023-02-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_pazarlar"),
    ]

    operations = [
        migrations.RenameField(model_name="pazarlar", old_name="EN", new_name="UK",),
    ]
