# Generated by Django 4.1.1 on 2023-01-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0003_data_maliyet"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order_Info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Last_Status",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("Last_Update", models.DateField(blank=True, null=True)),
                (
                    "Tracknumber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.data",
                    ),
                ),
            ],
        ),
    ]
