# Generated by Django 4.1.1 on 2023-01-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_data_maliyet"),
        ("order_track", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order_info",
            name="Order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.data",
            ),
        ),
        migrations.AlterField(
            model_name="order_info",
            name="Tracknumber",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
