# Generated by Django 4.1.1 on 2023-01-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_track", "0003_rename_order_info_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="Courier_Name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
