# Generated by Django 4.1.1 on 2023-01-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_track", "0004_order_courier_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderFileData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
