# Generated by Django 4.1.1 on 2023-01-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_track", "0007_alter_order_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="Order", new_name="Data_Order",
        ),
    ]
