# Generated by Django 4.1.1 on 2023-01-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_track", "0010_rename_data_order_order_amazonorderid"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="Last_Update",),
    ]
