# Generated by Django 4.1.1 on 2023-02-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_track', '0011_remove_order_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Tracknumber2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
