# Generated by Django 4.1.1 on 2023-02-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_track', '0012_order_tracknumber2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
